### PR TITLE
fix issue where stdout and stderr are empty for quick exiting processes

### PR DESCRIPTION
**Pull request by jamestyrrell**
By not initializing the buffers prior to exiting stdout and stderr are empty. By including a 1000ms sleep straight after line 250 is executed and running a short running process `google-chrome --version` the issue can be replicated.

A simple test case is inlined below but requires the addition of the aforementioned sleep in order to reliably simulate a fast exiting process.

```
package com.test;

import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.concurrent.TimeUnit;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import com.zaxxer.nuprocess.NuAbstractProcessHandler;
import com.zaxxer.nuprocess.NuProcess;
import com.zaxxer.nuprocess.NuProcessBuilder;

public class ChromeTest {

  public static void main(String[] args) throws InterruptedException {
    for (int i = 0; i < 100; i++) {
      System.out.println();
      ChromeTest.create();
      System.out.println();
    }
  }

  private static class OS {
    public static final boolean IS_MAC;
    public static final boolean IS_LINUX;

    static {
      String os = System.getProperty("os.name").toLowerCase();
      IS_MAC = (os.contains("mac"));
      IS_LINUX = (os.contains("linux"));
    }

    private OS() {
    }
  }

  private static class OutputCollectingHandler extends NuAbstractProcessHandler {

    private final StringBuilder stdout = new StringBuilder();
    private final StringBuilder stderr = new StringBuilder();

    @Override
    public void onPreStart(NuProcess nuProcess) {
      System.out.println("onPreStart(" + nuProcess + ")");
      super.onPreStart(nuProcess);
    }

    @Override
    public void onStdout(ByteBuffer buffer, boolean closed) {
      if (buffer == null) {
        return;
      }
      CharSequence value = StandardCharsets.UTF_8.decode(buffer);
      System.out.println("onStdout(" + value + ")");
      stdout.append(value);
    }

    @Override
    public void onStderr(ByteBuffer buffer, boolean closed) {
      if (buffer == null) {
        return;
      }
      CharSequence value = StandardCharsets.UTF_8.decode(buffer);
      System.out.println("onStderr(" + value + ")");
      stderr.append(value);
    }

    @Override
    public void onExit(int statusCode) {
      System.out.println("onExit(" + statusCode + ")");
    }

    @Override
    public void onStart(NuProcess nuProcess) {
      System.out.println("onStart(" + nuProcess + ")");
    }

    public String getStdout() {
      System.out.println("getStdout()");
      return stdout.toString();
    }

    public String getStderr() {
      System.out.println("getStderr()");
      return stderr.toString();
    }
  }

  public final String chromeBinary;
  public final String chromeVersion;

  public ChromeTest(String chromeBinary, String chromeVersion) {
    this.chromeBinary = chromeBinary;
    this.chromeVersion = chromeVersion;
  }

  public static ChromeTest create() throws InterruptedException {
    String chromeBinary = determineChromeBinary();
    String chromeVersion = determineChromeVersion(chromeBinary);
    return new ChromeTest(chromeBinary, chromeVersion);
  }

  private static String determineChromeVersion(String chromeBinary) throws InterruptedException {
    OutputCollectingHandler handler = new OutputCollectingHandler();
    NuProcessBuilder pb = new NuProcessBuilder(Arrays.asList( //
        chromeBinary, //
        "--version" //
    ));
    pb.setProcessListener(handler);
    int status = pb.start().waitFor(30, TimeUnit.SECONDS);
    if (status != 0) {
      throw new RuntimeException("failed to get chrome version: status " + status + " stdout: " +
          handler.getStdout() + " stderr: " + handler.getStderr());
    }
    String chromeVersionOutput = handler.getStdout().trim();
    Pattern pattern = Pattern.compile("Google Chrome ([^/.]+).*");
    Matcher m;
    if (!(m = pattern.matcher(chromeVersionOutput)).matches()) {
      throw new RuntimeException("unexpected chrome --version output: '" + chromeVersionOutput +
          "' stdout: '" + handler.getStdout() + "' stderr: '" + handler.getStderr() + "'");
    }
    return m.group(1);
  }

  private static String determineChromeBinary() {
    return OS.IS_LINUX
        ? "/opt/google/chrome/chrome"
        : "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";
  }
}
```

### CODE REVIEW

**Comment by brettwooldridge** [comment]
Can you squash these two commits?

**Comment by jamestyrrell** [comment]
Yup, done.

**Comment by jamestyrrell** [comment]
Thanks @brettwooldridge, any chance of quick 1.0.1 release containing this fix?

**Comment by brettwooldridge** [comment]
Done.  The artifact has been published to the sonatype repository.  It might be available now as a dependency, but it takes a few hours before it appears in the search index.

**Comment by jamestyrrell** [comment]
:dancer: :+1: :100:

**Comment by bhamiltoncx** [comment]
This appears to have regressed quick-exiting processes on Linux (but not Mac) for me. Here's a repro.

```
% uname
Linux

% cat QuickExiting.java
import com.zaxxer.nuprocess.NuAbstractProcessHandler;
import com.zaxxer.nuprocess.NuProcess;
import com.zaxxer.nuprocess.NuProcessBuilder;

import java.nio.ByteBuffer;
import java.nio.channels.Channels;
import java.nio.channels.WritableByteChannel;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.concurrent.TimeUnit;

public class QuickExiting {
  private static class Handler extends NuAbstractProcessHandler {
    private static final WritableByteChannel STDERR = Channels.newChannel(System.err);

    @Override
    public void onExit(int exitCode) {
      System.err.format("Exited with code %d\n", exitCode);
      System.err.flush();
    }

    @Override
    public void onStdout(ByteBuffer buffer, boolean closed) {
      try {
        System.err.format("onStdout buf remaining %d closed %s\nGot bytes: [", buffer.remaining(), closed);
        System.err.flush();
        STDERR.write(buffer);
        System.err.format("]\n");
        System.err.flush();
      } catch (Exception e) {
        e.printStackTrace(System.err);
        System.exit(1);
      }
    }
  }
  public static void main(String[] args) {
    try {
      Path tmpFilePath = Files.createTempFile("nuprocess", "txt");
      Files.write(tmpFilePath, "Hello world!\n".getBytes("UTF-8"));
      try {
        Handler handler = new Handler();
        NuProcess process = new NuProcessBuilder(handler, "cat", tmpFilePath.toString()).start();
        int retVal = process.waitFor(Long.MAX_VALUE, TimeUnit.SECONDS);
        System.err.format("Process exited with code %d\n", retVal);
      } finally {
        Files.delete(tmpFilePath);
      }
    } catch (Exception e) {
      e.printStackTrace(System.err);
      System.exit(1);
    }
  }
}

% javac -cp jna-4.1.0.jar:nuprocess-1.0.3-SNAPSHOT.jar QuickExiting.java
% java -cp jna-4.1.0.jar:nuprocess-1.0.3-SNAPSHOT.jar:. QuickExiting     
onExit: 0
onStdout buf remaining 0 closed true
Got bytes: []
Exited with code 0
Process exited with code 0
```

Mac example:

```
% uname
Darwin
% javac -cp jna-4.1.0.jar:nuprocess-1.0.3-SNAPSHOT.jar QuickExiting.java
% java -cp jna-4.1.0.jar:nuprocess-1.0.3-SNAPSHOT.jar:. QuickExiting
onStdout buf remaining 13 closed false
Got bytes: [Hello world!
]
onStdout buf remaining 0 closed true
Got bytes: []
Exited with code 0
Process exited with code 0
```

I'll see if I can provide a fix.

**Comment by bhamiltoncx** [comment]
I confirmed reverting a931018fb3679dc3d057cee36f0e929cc8bf3173 makes this test pass. Looking to see what caused the regression. I'll provide a patch and a test.

**Comment by bhamiltoncx** [comment]
Test and fix in #40.

**Pull request merged**
