### PR TITLE
Remove linux process reap and let BaseEventProcessor do its job

### PR DESCRIPTION
**Pull request by jamestyrrell**
@brettwooldridge We are still experiencing the same issue. I have dived into the code a bit more and it looks like that by exiting early the pipes are never written as the process is never registered. I am removed the early exit bit and now `BaseEventProcessor` is able to do its job.

### CODE REVIEW

**Comment by brettwooldridge** [comment]
@jamestyrrell What is your confidence level on this?  Have you really beaten on this change?

**Comment by brettwooldridge** [comment]
Is the pull request obsoleted by pull #40?

**Comment by jamestyrrell** [comment]
It will be, but I am not sure that catching an early exit is the best course of action. Why not just let `BaseEventProcessor` handle it?

**Comment by brettwooldridge** [comment]
@jamestyrrell You can take another shot at it.

For certain Linux spawn failures, the [rc value](https://github.com/brettwooldridge/NuProcess/blob/master/src/main/java/com/zaxxer/nuprocess/internal/BasePosixProcess.java#L322) will be 0, and the [pid value](https://github.com/brettwooldridge/NuProcess/blob/master/src/main/java/com/zaxxer/nuprocess/internal/BasePosixProcess.java#L322) possibility 0 or undeterminable.

Removing the existing logic will result in ``registerProcess()`` getting called, which is likely to [encounter an issue here](https://github.com/brettwooldridge/NuProcess/blob/master/src/main/java/com/zaxxer/nuprocess/linux/ProcessEpoll.java#L79) because it relies on the ``pid``.  The ``cleanupProcess()`` and ``checkDeadPool()`` methods will similarly encounter issues [here](https://github.com/brettwooldridge/NuProcess/blob/master/src/main/java/com/zaxxer/nuprocess/linux/ProcessEpoll.java#L222),  [here](https://github.com/brettwooldridge/NuProcess/blob/master/src/main/java/com/zaxxer/nuprocess/linux/ProcessEpoll.java#L222), and [here](https://github.com/brettwooldridge/NuProcess/blob/master/src/main/java/com/zaxxer/nuprocess/linux/ProcessEpoll.java#L275).

Finally, if the ``NuProcessBuilder.start()`` method returns without exception, the user may call ``waitFor()`` or other methods that expect a valid ``pid``, and there is nothing we can do to protect them currently.

**Comment by brettwooldridge** [comment]
The last issue above, that of returning from ``start()`` without exception, might cause issues if the user calls ``wantWrite()`` or ``stdinWrite()`` on the non-spawned process.  You would need to test what happens in those cases.

**Pull request closed without merging**
