### PR TITLE
Add Automatic-Module-Name manifest entry to make NuProcess module-system-friendly

### PR DESCRIPTION
**Pull request by timboudreau**
A trivial PR that simply adds a manifest entry for `Automatic-Module-Name` which makes it possible to use this library from modular Java libraries and get a result that is safe to publish on Maven central.

### CODE REVIEW

**Comment by bturner** [comment]
I made a small whitespace tweak to keep the POM consistent, but other than that, looks good to me. Thanks for the contribution @timboudreau.

**Comment by jonathanl-telenav** [comment]
Thanks for NuProcess.

**Comment by bturner** [comment]
Credit to @brettwooldridge for that; I'm just trying to help with the maintenance.

I'll need to refresh my memory on how to do the release process for this; it's been a minute since I released 2.0.3 (which I'm realizing I forgot to push the tag for)

**Comment by timboudreau** [comment]
Is there a general plan for when there might be a release that incorporates this change?

Happy to contribute any effort that would be helpful.  The current snapshot version is working well for us, and I would like to release [our branch that migrates our maven plugin to use NuProcess to run its external processes](https://github.com/telenav/cactus/tree/nuprocess), but we need a modular release on Maven central to link against.

**Comment by bturner** [comment]
I'll try to get 2.0.4 out this week

**Comment by timboudreau** [comment]
That's awesome!  Thank you!

**Comment by bturner** [comment]
2.0.4 has been released. It may take a little while to be fully published on Central.

**Pull request merged**
